### ISSUE TITLE
sw_combine.R strange check

### ISSUE THREAD

**Issue by RonaldVisser** [hanecakr/fellingdateR#5]
The check between lines 90-99 is atypical in comparison with the checks before. Waney edge is corrected and only a warning is given, while the other tests are aimed at testing and then stopping.

**Comment by hanecakr** [comment]
Hi Ronald,

This 'correction' was inspired by .fh files that were created with TSAP (Rinntech) software. There you can choose between WKL, WKE, WK? and WKX as entries for 'Waldkante/waneyedge'. And these values are extracted by the 'read_fh' function in fellingdateR.
'sw_combine()' needs a logical TRUE/FALSE for the waneyedge variable. Hence the converstion to TRUE/FALSE. But I should make this conversion optional and set it as one of the function-parameters.

It's on the todo-list!

Much appreciated.

- Kristof.
